# -*- coding: utf-8 -*-
"""text to image

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dtUKzjdbjy7L0c6q7TY3A-PwZvniJPyx
"""

!pip install  --upgrade diffusers transformers -q

from diffusers import StableDiffusionPipeline
import torch

# Configuration class
class CFG:
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    seed = 42
    generator = torch.Generator(device).manual_seed(seed)
    image_gen_steps = 35
    image_gen_model_id = 'CompVis/stable-diffusion-v1-4'  # Ensure to use a valid model

# Load the model
model_id = CFG.image_gen_model_id
pipe = StableDiffusionPipeline.from_pretrained(model_id, variant="fp16",torch_dtype=torch.float16)
pipe = pipe.to(CFG.device)

# Function to generate image
def generate_image(prompt, model):
    image = model(
        prompt,
        num_inference_steps=CFG.image_gen_steps,
        generator=CFG.generator,
        guidance_scale=7.5  # Adjust as needed
    ).images[0]
    return image

# Generate and display the image
image = generate_image('black cat with red eyes', pipe)

generate_image('Astronaut in space station', pipe)

